---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: Ao migrar dados de armazenamento, os backends de armazenamento são integrados manualmente usando APIs REST.  Ao migrar dados do VASA Provider, os dados são exportados do banco de dados Derby existente e importados para o banco de dados MongoDB. 
---
= Migrar o Provedor VASA e atualizar o SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga os passos desta seção para migrar o provedor VASA das ONTAP tools for VMware vSphere 9.xx para as ONTAP tools for VMware vSphere 10.4 e atualizar o Adaptador de Replicação de Armazenamento (SRA) no dispositivo VMware Live Site Recovery.



== Etapas para migrar o provedor VASA

. Para habilitar o Derby PORT 1527 nas ONTAP tools for VMware vSphere, habilite o usuário root e faça login na CLI via SSH.  Em seguida, execute o seguinte comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implante o OVA para ONTAP tools for VMware vSphere 10.4.
. Adicione a instância do vCenter Server que você deseja migrar para as ONTAP tools for VMware vSphere 10.4. Consulte link:../configure/add-vcenter.html["Adicionar uma instância do vCenter Server"] para maiores informações.
. Integre o backend de armazenamento localmente a partir das APIs do servidor vCenter para o plug-in de ferramentas ONTAP . Consultelink:../configure/add-storage-backend.html["Adicione um backend de armazenamento usando a interface do cliente vSphere."] Para obter mais informações.
. Obtenha um token de acesso para autenticar solicitações à API REST. Utilize o exemplo a seguir, substituindo as variáveis por valores específicos do seu ambiente.
+
+



[listing]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
Copie e salve o token de acesso retornado na resposta. . Emita a seguinte API do Swagger ou no Postman para migrar.

+

[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
Você pode acessar o Swagger através deste URL: `\https://$FQDN_IP_PORT/`, por exemplo: `\https://10.67.25.33:8443/`.

+

[]
====
*Método HTTP e ponto final*

Esta chamada de API REST usa o seguinte método e endpoint.

|===


| *Método HTTP* | *Caminho* 


| PUBLICAR | /api/v1 
|===
*Tipo de processamento*

Assíncrono

*Exemplo de ondulação*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
--header 'x-auth: <auth_token>' \
--header 'Content-Type: application/json' \
--data '{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "******"
  },
  "database_password": "******"
}'
----
Corpo da solicitação para migração de outra versão:

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
*Exemplo de saída JSON*

O sistema retorna um objeto de trabalho. Salve o identificador do trabalho para usá-lo na próxima etapa.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. Use o seguinte URI no Swagger para verificar o status:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<migration_id>?includeSubJobsAndTasks=true`
----
+
Após a conclusão do trabalho, revise o relatório de migração na resposta do trabalho.

. Adicione as ONTAP tools for VMware vSphere ao vCenter Server.
. Registre o provedor VASA com as ONTAP tools for VMware vSphere. Para obter instruções, consultelink:../configure/registration-process.html["Registre o Provedor VASA"] .
. Após o registro, verifique o nome do provedor VASA e seu status no vSphere Client em *Provedores de armazenamento*. O provedor VASA deverá aparecer online, confirmando o registro bem-sucedido.
. link:../manage/enable-services.html["Habilitar provedor VASA"]serviço em ONTAP tools for VMware vSphere 10.4.
. Pare as ONTAP tools for VMware vSphere 9.10/9.11/9.12/9.13 VASA seguindo estes passos:
+
.. Nas ferramentas ONTAP 9.x, abra o console da web.
.. Acesse o console de manutenção.
.. Digitar `1` Para selecionar o menu *Configuração do Aplicativo*.
.. Digitar `5` interromper os serviços do provedor VASA e do SRA.
.. No vSphere Client, navegue até *Inventário* > *Provedores de armazenamento*.
.. Selecione o provedor VASA do ONTAP tools 9.x no backend de armazenamento e clique em *Remover*.
+
Após a interrupção do antigo Provedor VASA, o vCenter Server faz failover para as ONTAP tools for VMware vSphere. Todos os datastores e VMs se tornam acessíveis e são atendidos pelas ONTAP tools for VMware vSphere.



. Os datastores NFS e VMFS migrados aparecem nas ONTAP tools for VMware vSphere 10.4 após o trabalho de descoberta do datastore, que pode levar até 30 minutos. Verifique a visibilidade deles na página de visão geral.
. Execute a migração do patch usando a seguinte API no Swagger ou no Postman:
+
[]
====
*Método HTTP e ponto final*

Esta chamada de API REST usa o seguinte método e endpoint.

|===


| *Método HTTP* | *Caminho* 


| CORREÇÃO | /api/v1 
|===
*Tipo de processamento*

Assíncrono

Utilize o seguinte URI no Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Exemplo de ondulação*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
*Exemplo de saída JSON*

Um objeto de trabalho é retornado.  Você deve salvar o identificador do trabalho para usá-lo na próxima etapa.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+
O corpo da solicitação está vazio para a operação de patch.




NOTE: UUID é o UUID de migração retornado em resposta à API pós-migração.

Após executar a API de migração de patches, todas as VMs estarão em conformidade com a política de armazenamento.

.O que vem a seguir
Após concluir a migração e registrar o ONTAP Tools 10.4 no vCenter Server, siga estas etapas:

* Aguarde a conclusão da *Descoberta* e o sistema atualizará os certificados automaticamente em todos os hosts.
* Aguarde antes de iniciar as operações do armazenamento de dados e da máquina virtual. O tempo de espera depende do número de hosts, armazenamentos de dados e máquinas virtuais. Se você não esperar, poderá ver falhas ocasionais.


Após a atualização, se o estado de conformidade da máquina virtual estiver desatualizado, reaplique a política de armazenamento usando as seguintes etapas:

. Acesse o armazenamento de dados e selecione *Resumo* > *Políticas de armazenamento de VM*.
+
O sistema mostra o status de conformidade em *Conformidade da política de armazenamento de VM* como *Desatualizado*.

. Selecione a política de VM de armazenamento e a VM correspondente.
. Selecione *Aplicar*.
+
O status de conformidade em *Conformidade da política de armazenamento de VM* é exibido como compatível. Informações relacionadas

+
** link:../concepts/rbac-learn-about.html["Saiba mais sobre as ONTAP tools for VMware vSphere 10 RBAC"]
** link:../upgrade/upgrade-ontap-tools.html["Atualização das ONTAP tools for VMware vSphere 10.x para 10.4"]






== Etapas para atualizar o adaptador de replicação de armazenamento (SRA)

.Antes de começar
No plano de recuperação, o site protegido refere-se ao local onde as VMs estão em execução, enquanto o site de recuperação é onde as VMs serão recuperadas. A interface do SRM exibe o estado do plano de recuperação com detalhes sobre os sites protegidos e de recuperação. No plano de recuperação, os botões *CleanupP* e *Reprotect* estão desabilitados, enquanto os botões TEST e RUN permanecem habilitados. Isso indica que o site está preparado para recuperação de dados. Antes de migrar o SRA, verifique se um site está no estado protegido e o outro no estado de recuperação.


NOTE: Não inicie a migração se o failover tiver sido concluído, mas a nova proteção estiver pendente. Certifique-se de que o processo de reproteção seja concluído antes de prosseguir com a migração. Se um failover de teste estiver em andamento, limpe-o e inicie a migração.

. Siga estas etapas para excluir o adaptador SRA das ferramentas ONTAP para VMware vSphere 9.xx no VMware Site Recovery:
+
.. Acesse a página de gerenciamento de configuração do VMware Live Site Recovery
.. Vá para a seção *Adaptador de Replicação de Armazenamento*.
.. No menu de reticências, selecione *Redefinir configuração*.
.. No menu de reticências, selecione *Excluir*.


. Execute essas etapas nos sites de proteção e recuperação.
+
.. link:../manage/enable-services.html["Habilitar ONTAP tools for VMware vSphere"]
.. Instale as ONTAP tools for VMware vSphere 10.4 SRA seguindo as etapas emlink:../protect/configure-on-srm-appliance.html["Configurar SRA no dispositivo VMware Live Site Recovery"] .
.. Na página de interface do usuário do VMware Live Site Recovery, execute as operações *Descobrir matrizes* e *Descobrir dispositivos* e confirme se os dispositivos são exibidos como antes da migração.



