---
permalink: protect/verify-the-replicated-storage-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Você deve verificar se o site protegido e o site de recuperação estão pareados com sucesso após configurar o Adaptador de Replicação de Armazenamento (SRA).  O sistema de armazenamento replicado deve ser detectável tanto pelo site protegido quanto pelo site de recuperação.' 
---
= Verificar sistemas de armazenamento replicados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve verificar se o site protegido e o site de recuperação estão pareados com sucesso após configurar o Adaptador de Replicação de Armazenamento (SRA).  O sistema de armazenamento replicado deve ser detectável tanto pelo site protegido quanto pelo site de recuperação.

.Antes de começar
* Você deve ter configurado seu sistema de armazenamento.
* Você deve ter pareado o site protegido e o site de recuperação usando o gerenciador de array do VMware Live Site Recovery.
* Você deve ter habilitado a licença FlexClone e a licença SnapMirror antes de executar a operação de failover de teste e a operação de failover para SRA.
* Você deve ter as mesmas políticas e programações do SnapMirror nos sites de origem e destino.


.Passos
. Efetue login no seu vCenter Server.
. Navegue até *Recuperação de Site* > *Replicação Baseada em Matriz*.
. Selecione o Par de Matriz necessário e verifique os detalhes correspondentes.
+
Os sistemas de armazenamento devem ser descobertos no site protegido e no site de recuperação com o status "`Habilitado`".


