---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Caso tenha esquecido a senha do Gerenciador de ferramentas ONTAP , você pode redefinir as credenciais do administrador usando o token gerado pelo console de manutenção das ONTAP tools for VMware vSphere . 
---
= Redefinir a senha do gerenciador de ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você esqueceu a senha do Gerenciador de ferramentas ONTAP , você pode redefinir as credenciais do administrador usando o token gerado pelo console de manutenção das ONTAP tools for VMware vSphere .

.Passos
. Inicie o ONTAP Tools Manager em um navegador da web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Na tela de login, selecione a opção *Redefinir senha*.
+
Para redefinir a senha do gerente, você precisa gerar o token de redefinição usando o console de manutenção das ONTAP tools for VMware vSphere .

+
.. No vCenter Server, abra o console de manutenção
.. Digite '2' para selecionar a opção Configuração do Sistema
.. Digite '3' para alterar a senha do usuário 'maint'.


. Na janela pop-up de alteração de senha, insira o token de redefinição de senha, o nome de usuário e os detalhes da nova senha.
. Selecione *Redefinir* para implementar as alterações.  Após a redefinição de senha bem-sucedida, você pode usar a nova senha para efetuar login.

